import OpenAI from "openai";
import type { StudentReportData } from "@/lib/report-data";

const openai = new OpenAI({ apiKey: process.env.OPENAI_API_KEY || "dummy-key-for-build" });

export interface SubjectRating {
    subject: string;
    score: number; // 0-10
    comment: string;
}

export interface QuestionSolution {
    assessment: string;
    round: string;
    question: string;
    verdict: string;       // e.g. "Correct", "Incorrect", "Partially correct (3/5 tests)"
    whatWentWrong: string; // empty if fully correct
    modelSolution: string; // ideal answer / correct code
}

export interface ReportAnalysis {
    executiveSummary: string;
    overallReadiness: string;
    subjectRatings: SubjectRating[];
    strengths: string[];
    weaknesses: string[];
    improvementAreas: string[];
    questionSolutions: QuestionSolution[];
    /** True when generated by fallback (AI unavailable / no assessments). */
    isFallback: boolean;
}

const clip = (s: unknown, n: number) => {
    const str = typeof s === "string" ? s : String(s ?? "");
    return str.length > n ? str.slice(0, n) + "…[truncated]" : str;
};

const MAX_QUESTIONS_IN_PROMPT = 45;

/**
 * Compresses the full assessment results into a bounded, information-rich digest for the LLM.
 * Keeps enough per-question context (the artifacts a solution can be derived from) while
 * capping code/text length and total question count so the prompt stays within budget.
 */
function buildDigest(data: StudentReportData): { digest: string; questionCount: number } {
    const lines: string[] = [];
    let questionCount = 0;

    for (const a of data.assessments) {
        lines.push(`\n### ASSESSMENT: ${a.title} (final score ${a.score}${a.autoSubmitted ? ", AUTO-SUBMITTED" : ""})`);
        for (const round of a.rounds) {
            const type = round.type;
            if (type === "mcq" || type === "aptitude") {
                const total = round.totalQuestions ?? round.questions?.length ?? 0;
                lines.push(`Round ${type.toUpperCase()}: ${round.correct ?? 0}/${total} correct${round.adaptive ? ` (adaptive, peak L${round.highestLevel ?? 1})` : ""}.`);
                for (const q of round.questions || []) {
                    if (questionCount >= MAX_QUESTIONS_IN_PROMPT) break;
                    const correct = q.selectedIndex === q.correctIndex;
                    const opts = (q.options || []).map((o: string, i: number) => `${String.fromCharCode(65 + i)}) ${clip(o, 120)}`).join("  ");
                    const chosen = q.selectedIndex == null ? "not answered" : String.fromCharCode(65 + q.selectedIndex);
                    const answer = q.correctIndex == null ? "?" : String.fromCharCode(65 + q.correctIndex);
                    lines.push(`- [${correct ? "RIGHT" : "WRONG"}] Q: ${clip(q.question, 300)} | Options: ${opts} | student chose ${chosen}, correct is ${answer}`);
                    questionCount++;
                }
            } else if (type === "coding") {
                lines.push(`Round CODING: solved ${round.solved ?? 0}/${round.total ?? 0} problems, ${round.passedTestCases ?? 0}/${round.totalTestCases ?? 0} test cases${round.adaptive ? ` (adaptive, peak L${round.highestLevel ?? 1})` : ""}.`);
                for (const p of round.problems || []) {
                    if (questionCount >= MAX_QUESTIONS_IN_PROMPT) break;
                    const samples = (p.testResults || []).slice(0, 3).map((t: any) => `in=${clip(t.input, 80)} expected=${clip(t.expected, 80)}`).join(" ; ");
                    lines.push(`- Problem: ${clip(p.title, 200)} | passed ${p.passedCount ?? 0}/${p.testCaseCount ?? 0} tests | sample cases: ${samples}`);
                    questionCount++;
                }
            } else if (type === "debug") {
                lines.push(`Round DEBUG (${round.language}): fixed ${round.solved ?? 0}/${round.total ?? 0}.`);
                for (const c of round.challenges || []) {
                    if (questionCount >= MAX_QUESTIONS_IN_PROMPT) break;
                    lines.push(`- Debug challenge: ${clip(c.title, 200)} | ${c.passed ? "FIXED" : "NOT FIXED"} (${c.passedCount ?? 0}/${c.testCaseCount ?? 0} tests) | student's final code:\n${clip(c.finalCode, 900)}`);
                    questionCount++;
                }
            } else if (type === "sql") {
                lines.push(`Round SQL: ${round.passedTestCases ?? 0}/${round.totalTestCases ?? 0} test cases passed.`);
                for (const q of round.questions || []) {
                    if (questionCount >= MAX_QUESTIONS_IN_PROMPT) break;
                    lines.push(`- SQL question: ${clip(q.title, 200)} | passed ${q.passedCount ?? 0}/${q.testCaseCount ?? 0} | student's query: ${clip(q.finalQuery, 400)}`);
                    questionCount++;
                }
            } else if (type === "output") {
                lines.push(`Round OUTPUT PREDICTION: ${round.correct ?? 0}/${round.totalQuestions ?? 0} correct.`);
                for (const q of round.questions || []) {
                    if (questionCount >= MAX_QUESTIONS_IN_PROMPT) break;
                    lines.push(`- [${q.correct ? "RIGHT" : "WRONG"}] Predict output of (${q.language}):\n${clip(q.code, 400)}\n  expected="${clip(q.expectedOutput, 200)}" student predicted="${clip(q.predicted, 200)}"`);
                    questionCount++;
                }
            } else if (type === "email") {
                lines.push(`Round EMAIL WRITING: score ${round.score ?? 0}/${round.maxScore ?? 0}.`);
                for (const q of round.questions || []) {
                    if (questionCount >= MAX_QUESTIONS_IN_PROMPT) break;
                    lines.push(`- Email task: ${clip(q.topic, 160)} | marks ${q.marks}/10 | grammar issues: ${q.grammarIssues ?? "?"} | examiner feedback: ${clip(q.feedback, 250)}`);
                    questionCount++;
                }
            } else if (type === "voice") {
                lines.push(`Round VOICE INTERVIEW: score ${round.score ?? 0}/${round.maxScore ?? 0}${round.adaptive ? ` (adaptive, peak L${round.highestLevel ?? 1})` : ""}.`);
                for (const q of round.questions || []) {
                    if (questionCount >= MAX_QUESTIONS_IN_PROMPT) break;
                    lines.push(`- Voice Q: ${clip(q.question, 200)} | marks ${q.marks}/5 | feedback: ${clip(q.feedback, 200)}`);
                    questionCount++;
                }
            }
        }
    }

    return { digest: lines.join("\n"), questionCount };
}

function fallbackAnalysis(reason: string): ReportAnalysis {
    return {
        executiveSummary:
            reason === "no-data"
                ? "This student has not attempted any assessments yet, so a performance-based analysis is not available. The activity and problem-solving sections of this report reflect their platform engagement."
                : "An automated skill analysis could not be generated at this time. The remainder of this report contains the student's full activity and assessment records.",
        overallReadiness: "Not enough assessment data to determine placement readiness.",
        subjectRatings: [],
        strengths: [],
        weaknesses: [],
        improvementAreas: [],
        questionSolutions: [],
        isFallback: true,
    };
}

export async function generateReportAnalysis(data: StudentReportData): Promise<ReportAnalysis> {
    const attempted = data.assessments.some((a) => a.rounds.length > 0);
    if (!attempted) {
        return fallbackAnalysis("no-data");
    }

    const { digest } = buildDigest(data);

    const system = `You are a senior technical placement assessor writing the analysis section of an official student evaluation report for a college's Training & Placement Officer. Be precise, professional, and evidence-based — cite specific questions/rounds from the data. Never invent facts not supported by the data.

You will receive a digest of every assessment the student attempted, question by question, including their answers, submitted code/queries, and per-test-case results.

Produce a JSON object with EXACTLY these keys:
{
  "executiveSummary": "2-4 sentence professional overview of the student's demonstrated ability",
  "overallReadiness": "1-2 sentences on placement readiness and the roles they suit",
  "subjectRatings": [ { "subject": "Mathematics / Quantitative Aptitude", "score": <0-10 number>, "comment": "one sentence justified by the data" }, ... ],
  "strengths": [ "specific strength grounded in the data", ... ],
  "weaknesses": [ "specific weakness grounded in the data", ... ],
  "improvementAreas": [ "actionable, specific advice the student can follow", ... ],
  "questionSolutions": [ { "assessment": "...", "round": "coding|debug|sql|output|mcq|aptitude|voice|email", "question": "short identifier of the question", "verdict": "Correct | Incorrect | Partially correct (x/y)", "whatWentWrong": "concrete explanation, empty string if fully correct", "modelSolution": "the correct answer; for coding/debug/sql/output give complete correct CODE in the right language" }, ... ]
}

Rules:
- subjectRatings: ONLY include subjects the assessments actually tested. Choose from: "Mathematics / Quantitative Aptitude", "Logical Reasoning", "Verbal Ability", "Coding & Problem Solving", "Debugging", "Databases (SQL)", "Code Comprehension (Output Prediction)", "Communication (Email/Voice)". Score each 0-10 from the evidence.
- questionSolutions: prioritise questions the student got WRONG or partially wrong. For every coding, debug, sql, and output-prediction question that was not fully correct, provide a complete, correct modelSolution as runnable code. Cover as many as the data supports (aim for thorough — this is the core of the report). For MCQ/aptitude the modelSolution is the correct option plus a one-line reason.
- Keep code solutions clean and idiomatic. Do NOT wrap code in markdown fences inside the JSON string.
- Return ONLY the JSON object.`;

    const user = `Student: ${data.student.name}
Assessments taken: ${data.assessments.length}
Internal problems solved on platform: ${data.stats.internalProblemsSolved}

===== PER-QUESTION ASSESSMENT DIGEST =====
${digest}`;

    try {
        const completion = await openai.chat.completions.create({
            model: "gpt-4o",
            messages: [
                { role: "system", content: system },
                { role: "user", content: user },
            ],
            response_format: { type: "json_object" },
            temperature: 0.4,
        });

        let content = completion.choices[0].message.content || "{}";
        content = content.replace(/```json\n?|```/g, "").trim();
        const parsed = JSON.parse(content);

        return {
            executiveSummary: typeof parsed.executiveSummary === "string" ? parsed.executiveSummary : "",
            overallReadiness: typeof parsed.overallReadiness === "string" ? parsed.overallReadiness : "",
            subjectRatings: Array.isArray(parsed.subjectRatings)
                ? parsed.subjectRatings
                      .filter((r: any) => r && typeof r.subject === "string")
                      .map((r: any) => ({
                          subject: r.subject,
                          score: Math.max(0, Math.min(10, Math.round(Number(r.score) || 0))),
                          comment: typeof r.comment === "string" ? r.comment : "",
                      }))
                      // Drop domains the model included but the assessments never tested
                      // (it sometimes adds a 0-score "not assessed" row despite instructions).
                      .filter((r: SubjectRating) => !(r.score === 0 && /\bnot\s+(assessed|tested|evaluated|covered|attempted|included)|\bno\s+.*(question|round|task)/i.test(r.comment)))
                : [],
            strengths: Array.isArray(parsed.strengths) ? parsed.strengths.filter((s: any) => typeof s === "string") : [],
            weaknesses: Array.isArray(parsed.weaknesses) ? parsed.weaknesses.filter((s: any) => typeof s === "string") : [],
            improvementAreas: Array.isArray(parsed.improvementAreas)
                ? parsed.improvementAreas.filter((s: any) => typeof s === "string")
                : [],
            questionSolutions: Array.isArray(parsed.questionSolutions)
                ? parsed.questionSolutions
                      .filter((q: any) => q && typeof q.question === "string")
                      .map((q: any) => ({
                          assessment: String(q.assessment ?? ""),
                          round: String(q.round ?? ""),
                          question: String(q.question ?? ""),
                          verdict: String(q.verdict ?? ""),
                          whatWentWrong: String(q.whatWentWrong ?? ""),
                          modelSolution: String(q.modelSolution ?? ""),
                      }))
                : [],
            isFallback: false,
        };
    } catch (err) {
        console.error("Report analysis generation failed:", err);
        return fallbackAnalysis("error");
    }
}
